# version: '3.8'
services:
  app:
    build: .
    ports:
      - '2005:3000'
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/toursDB
    command: npm run start:dev # or npm run start

  mongo:
    image: mongo:6
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
